### ISSUE TITLE
Some bookmarks hidden in the Bookmark Panel

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#632]
#### Expected behavior

I expect to be shown my Bookmarked posts fully.

#### Actual behavior

Some of the bookmarks are hidden if they are more than 9 in the bottom of the bookmark page.

#### How to reproduce

- Open app & Login
- Bookmark upto 8 posts
- Go-to Menu > Bookmarks
- Scroll Up and Down

***
* App version: v2.0.8
* Operating system: Android 8.0.1
***

#### Recording Of The Bug
<img src="https://i.ibb.co/6X4Sdc5/G-20190226-0024362.gif" alt="G-20190226-0024362" border="0">

**Comment by ue** [comment]
@mistikk I fixed for the weight things can you check also forheight on android for ios is okay

**Comment by horpeyloaded** [comment]
Not fixed @ue @mistikk

**Comment by ue** [comment]
@mistikk can you please take a look on android

**Comment by mistikk** [comment]
I can not repreduce @horpeyloaded @ue 
![image](https://user-images.githubusercontent.com/8211075/54753290-b78a3380-4bf1-11e9-8109-d6b1cd0ae3c7.png)

**Comment by horpeyloaded** [comment]
add more than 9 bookmarks and see @mistikk

**Comment by mistikk** [comment]
This issue has been solved in our latest update, can you check from below links and if it is okay for you or you have any feedback please let me know, thank you :) @horpeyloaded 

iOS : install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/internal
Android : install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/internal

**Comment by horpeyloaded** [comment]
@mistikk, eSteem appkeeps stopping on my phone. Check ✔ the build plz

**Comment by mistikk** [comment]
@horpeyloaded fixed, can you check again?

**Comment by horpeyloaded** [comment]
@mistikk please check it very well to see it's working; it’s not fixed and I have limited internet cap over here.

**Comment by mistikk** [comment]
@horpeyloaded did you remove and reinstall application, if you didnt, can you remove and try again, Fil got same error yesterday and it resolved like this

**Comment by horpeyloaded** [comment]
I can use the app now but still not fixed @mistikk

**Comment by mistikk** [comment]
@horpeyloaded I've been investigate for a few days, I tried on different android devices but we can not reproduce so we can not find what is a problem. Maybe it is related from these posts, can you share your bookmark posts links I want to try with those posts. And also maybe you can remove all posts and add them back.

**Comment by mistikk** [comment]
@horpeyloaded can you test last release for this issue

**Comment by ue** [comment]
@horpeyloaded did you test again? I am closing now if you see this error after test please re-open
